In [3]:
try:
  print(x)
except:
  print("An exception occurred")
  x = 10

10


In [1]:

import numpy as np
 
# using loadtxt()
arr = np.loadtxt("position_space.csv",
                 delimiter=",", dtype=float)
display(arr)

array([ -1.  ,   1.44,  25.2 ,   1.2 ,  12.48,   0.24, -21.36,   4.08,
       -12.48,   1.44,  25.44,   1.2 ,  12.48,   0.24,  -3.36,   0.72,
        -2.88,   1.44,  25.2 ,   1.2 ,  12.48,   0.24, -21.36,   4.08,
       -12.48])

In [2]:
len(arr)
arr = np.delete(arr, 0).reshape(-1, 8)

In [3]:
arr

array([[  1.44,  25.2 ,   1.2 ,  12.48,   0.24, -21.36,   4.08, -12.48],
       [  1.44,  25.44,   1.2 ,  12.48,   0.24,  -3.36,   0.72,  -2.88],
       [  1.44,  25.2 ,   1.2 ,  12.48,   0.24, -21.36,   4.08, -12.48]])

In [4]:
from math import sin, cos, pi
from pylx16a.lx16a import *
import time
import numpy as np
from scipy import interpolate
import try_wave as ctrl
def get_BSpline_command(num_of_points, phase_difference):
    position_space = np.genfromtxt("position_space.csv", delimiter=",") #for reading
    position_space = np.delete(position_space, 0).reshape(-1, 8)
    left = position_space[:, 4:8]

    run_command = np.array([])

    for i in range(4):
        x = np.linspace(1, 10, len(left[:, i]))
        tck = interpolate.splrep(x, left[:, i], s=0, k=2) 
        x_new = np.linspace(min(x), max(x), num_of_points)
        y_fit = interpolate.BSpline(*tck)(x_new)
        run_command = np.append(run_command, y_fit)
    run_command = run_command.reshape(4, -1) #this is the right leg command
    run_command[0] = 0
    run_command = np.transpose(run_command)

    run_command_left = -1 * np.concatenate((run_command[phase_difference:num_of_points, :],run_command[0:phase_difference, :]), axis = 0) # this is the left leg
    run_command = np.concatenate((run_command_left, run_command), axis=1) # run command is a n*6 matrix
    return run_command

In [5]:
b = get_BSpline_command(5, phase_difference=1)

In [6]:
b

array([[ -0.  ,   7.86,  -1.56,   5.28,   0.  , -21.36,   4.08, -12.48],
       [ -0.  ,   3.36,  -0.72,   2.88,   0.  ,  -7.86,   1.56,  -5.28],
       [ -0.  ,   7.86,  -1.56,   5.28,   0.  ,  -3.36,   0.72,  -2.88],
       [ -0.  ,  21.36,  -4.08,  12.48,   0.  ,  -7.86,   1.56,  -5.28],
       [ -0.  ,  21.36,  -4.08,  12.48,   0.  , -21.36,   4.08, -12.48]])

In [7]:
np.delete(b, 0)
b

array([[ -0.  ,   7.86,  -1.56,   5.28,   0.  , -21.36,   4.08, -12.48],
       [ -0.  ,   3.36,  -0.72,   2.88,   0.  ,  -7.86,   1.56,  -5.28],
       [ -0.  ,   7.86,  -1.56,   5.28,   0.  ,  -3.36,   0.72,  -2.88],
       [ -0.  ,  21.36,  -4.08,  12.48,   0.  ,  -7.86,   1.56,  -5.28],
       [ -0.  ,  21.36,  -4.08,  12.48,   0.  , -21.36,   4.08, -12.48]])

In [8]:
try:
    servo_start_angle = np.loadtxt("position_space.csv", dtype=float)
    servo_start_angle = np.delete(servo_start_angle, 0).reshape(-1, 8)
except:
    servo_start_angle =  np.asarray([ 93.36,  88.8,  107.04, 112.56, 130.56, 122.4,  127.92,  84.])
    print("Unable to find the initial position.csv, set the position to default")

In [9]:
servo_start_angle

array([[  1.44,  25.2 ,   1.2 ,  12.48,   0.24, -21.36,   4.08, -12.48],
       [  1.44,  25.44,   1.2 ,  12.48,   0.24,  -3.36,   0.72,  -2.88],
       [  1.44,  25.2 ,   1.2 ,  12.48,   0.24, -21.36,   4.08, -12.48]])

In [33]:

num_of_points = 10
phase_difference = 5
position_space = np.genfromtxt("position_space.csv", delimiter=",") #for reading
position_space = np.delete(position_space, 0).reshape(-1, 8)
# run_command = position_space
print(position_space)
# left = position_space[:, 4:8]

run_command = np.array([])

for i in range(8):
    x = np.linspace(1, 10, len(position_space[:, i]))
    print(x)
    tck = interpolate.splrep(x, position_space[:, i], s=0, k=2) 
    print(tck)
    x_new = np.linspace(min(x), max(x), num_of_points)
    print(x_new)
    y_fit = interpolate.BSpline(*tck)(x_new)
    print(position_space)
    run_command = np.append(run_command, y_fit)
run_command = run_command.reshape(8, -1) #this is the right leg command
# run_command[0] = 0
run_command = np.transpose(run_command)

# run_command_left = -1 * np.concatenate((run_command[phase_difference:num_of_points, :],run_command[0:phase_difference, :]), axis = 0) # this is the left leg
# run_command = np.concatenate((run_command_left, run_command), axis=1) # run command is a n*6 matrix

[[  1.44  25.2    1.2   12.48   0.24 -21.36   4.08 -12.48]
 [  1.44  25.44   1.2   12.48   0.24  -3.36   0.72  -2.88]
 [  1.44  25.2    1.2   12.48   0.24 -21.36   4.08 -12.48]]
[ 1.   5.5 10. ]
(array([ 1.,  1.,  1., 10., 10., 10.]), array([1.44, 1.44, 1.44, 0.  , 0.  , 0.  ]), 2)
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[[  1.44  25.2    1.2   12.48   0.24 -21.36   4.08 -12.48]
 [  1.44  25.44   1.2   12.48   0.24  -3.36   0.72  -2.88]
 [  1.44  25.2    1.2   12.48   0.24 -21.36   4.08 -12.48]]
[ 1.   5.5 10. ]
(array([ 1.,  1.,  1., 10., 10., 10.]), array([25.2 , 25.68, 25.2 ,  0.  ,  0.  ,  0.  ]), 2)
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[[  1.44  25.2    1.2   12.48   0.24 -21.36   4.08 -12.48]
 [  1.44  25.44   1.2   12.48   0.24  -3.36   0.72  -2.88]
 [  1.44  25.2    1.2   12.48   0.24 -21.36   4.08 -12.48]]
[ 1.   5.5 10. ]
(array([ 1.,  1.,  1., 10., 10., 10.]), array([1.2, 1.2, 1.2, 0. , 0. , 0. ]), 2)
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[[  1.44  25.2    1.2   1

In [32]:
run_command

array([[  1.44      ,  25.2       ,   1.2       ,  12.48      ,
          0.24      , -21.36      ,   4.08      , -12.48      ],
       [  1.44      ,  25.29481481,   1.2       ,  12.48      ,
          0.24      , -14.24888889,   2.75259259,  -8.68740741],
       [  1.44      ,  25.36592593,   1.2       ,  12.48      ,
          0.24      ,  -8.91555556,   1.75703704,  -5.84296296],
       [  1.44      ,  25.41333333,   1.2       ,  12.48      ,
          0.24      ,  -5.36      ,   1.09333333,  -3.94666667],
       [  1.44      ,  25.43703704,   1.2       ,  12.48      ,
          0.24      ,  -3.58222222,   0.76148148,  -2.99851852],
       [  1.44      ,  25.43703704,   1.2       ,  12.48      ,
          0.24      ,  -3.58222222,   0.76148148,  -2.99851852],
       [  1.44      ,  25.41333333,   1.2       ,  12.48      ,
          0.24      ,  -5.36      ,   1.09333333,  -3.94666667],
       [  1.44      ,  25.36592593,   1.2       ,  12.48      ,
          0.24      ,  -8.9155555